language: android
android:
  components:
    - tools
    - platform-tools

    - build-tools-25.0.2
    - android-23

    # System images to run emulator during tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
before_install:
    - chmod +x gradlew